kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: unique-ip
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
      targetPort: 21
    - name: data
      port: 20
      targetPort: 20
    - name: min
      port: 30020
      targetPort: 30020
    - name: max
      port: 30021
      targetPort: 30021
  type: LoadBalancer

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftps-deployment
  labels:
    app: ftps

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps

  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 30020
            - containerPort: 30021
          livenessProbe:
            exec:
              command:
                - sh
                - health.sh
            initialDelaySeconds: 5
            periodSeconds: 1
