kind: Service
apiVersion: v1

metadata:
  name: influxdb-service
  labels:
    app: influxdb

spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: influxdb-deployment
  labels:
    app: influxdb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb

  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc

      containers:
        - name: influxdb
          image: influxdb-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-volume
              mountPath: /root/.influxdb

 
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-pvc
spec:
  resources:
    requests:
      storage: 512M
  accessModes:
    - ReadWriteOnce
