apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - name: wordpress
      port: 5050
      protocol: TCP
      targetPort: 5050
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  
  template:
    metadata:
      labels:
        app: wordpress
    
    spec:
      containers:
      - name: wordpress
        image: moboustt/wp
        imagePullPolicy: Never
        ports:
        - containerPort: 5050